### PR TITLE
config: recreate config according to JM v0.9.9

### PR DESCRIPTION
**Pull request by theborakompanioni**
Updates config property `directory_nodes` as per https://github.com/JoinMarket-Org/joinmarket-clientserver/commit/ebdbac7e9855bedc2627fc5ad71630973901202d

### CODE REVIEW

**Comment by theborakompanioni** [comment]
Blocked till it becomes officially released with a new upstream version (probably v0.9.9).

**Comment by theborakompanioni** [comment]
Adhere to merged config changes: 
- https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1374 
- https://github.com/JoinMarket-Org/joinmarket-clientserver/pull/1422

**Comment by theborakompanioni** [comment]
Unblocked as [`v0.9.9` has been released](https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.9.9).

**Review by dergigi — APPROVED** [review]
Looks good to me ✅

**Pull request merged**
